### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by pepicrft** [gestaltjs/gestalt#2]
The goal of this task is to add an[ issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) to guide contributors towards a more standard issue and PRs' structure.

**Comment by josemasar** [comment]
Here is my proposal for a Pull Request template:

1. Purpose
2. Related work items (linking with `#`) 
3. UI/UX changes 
4. Testing
